# -*- coding: utf-8 -*-
"""gpt1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-MSIo6lk3BnoddvXvMUObss-wB98LUZf
"""

import os

# Construct the full path using os.path.join
file_path = os.path.join("tiny-shakespeare-input.txt")

with open(file_path, 'r', encoding='utf-8') as f:
  text = f.read()

print("len=", len(text))
chars = sorted(list(set(text)))
print("chars=", chars)
vocab_size = len(chars)
print("vocab_size=", vocab_size)

stoi = { ch:i for i, ch in enumerate(chars) }
itos = { i:ch for i, ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("hii there"))
print(decode(encode("hii there")))
print(decode([33, 41]))

import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])

n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

block_size = 8
train_data[:block_size+1]
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  #print(f"when input is {context} the target: {target}")

torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
  data = train_data if split == 'train' else val_data
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])

  return x, y

xb, yb = get_batch("train")
print(xb.shape, yb.shape)
print(xb)
print(yb)
for b in range(batch_size):
  for t in range(block_size):
    context = xb[b, :t+1]
    target = yb[b, t]
    #print(f"when input is {context.tolist()} the target: {target}")

import torch.nn as nn
from torch.nn import functional as F

torch.manual_seed(1337)

class BigramLM(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)
    print(self.token_embedding_table)

  def forward(self, idx, targets=None):
    logits = self.token_embedding_table(idx)
    #print("logits shape=", logits.shape)
    #print("------")
    loss = None
    if targets is not None:
      B, T, C = logits.shape
      #print("BTC=", B, T, C)
      logits = logits.view(B*T, C)
      #print("logits shape=", logits.shape)
      targets = targets.view(B*T)
      #print("targets shape=", targets.shape)
      # print("targets=", targets)
      loss = F.cross_entropy(logits, targets)
    return logits, loss

  def generate(self, idx, max_new_tokens):
    for _ in range(max_new_tokens):
      logits, loss = self(idx)
      logits = logits[:, -1, :]
      probs = F.softmax(logits, dim=-1)
      idx_next = torch.multinomial(probs, num_samples=1)
      idx = torch.cat((idx, idx_next), dim=1)
    return idx

m = BigramLM(vocab_size)
out, loss = m(xb, yb)
print("out=", out.shape)
print("loss=", loss)

idx = torch.zeros((1, 1), dtype=torch.long)
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))

print(m.parameters())
print("-----")
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)
batch_size = 32
for steps in range(10000):
  xb, yb = get_batch("train")
  #print("step=", steps, "weight1=", m.token_embedding_table(torch.tensor([13])))
  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())

idx = torch.zeros((1, 1), dtype=torch.long)
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))